In [1]:
import numpy as np
d3=np.arange(50).reshape(5,5,2)
d3                      

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [2]:
d3[0,2:4,1:3]

array([[5],
       [7]])

In [3]:
d3[1:,4:,0:]

array([[[18, 19]],

       [[28, 29]],

       [[38, 39]],

       [[48, 49]]])

In [4]:
d3[0:,2:4,1:3]

array([[[ 5],
        [ 7]],

       [[15],
        [17]],

       [[25],
        [27]],

       [[35],
        [37]],

       [[45],
        [47]]])

In [5]:
d3[1:,0:,1:2]

array([[[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]],

       [[31],
        [33],
        [35],
        [37],
        [39]],

       [[41],
        [43],
        [45],
        [47],
        [49]]])

In [6]:
x=np.array([1,3,4])
y=np.array([[1],[3],[4]])

In [7]:
x       

array([1, 3, 4])

In [8]:
y

array([[1],
       [3],
       [4]])

In [9]:
x,y=np.broadcast_arrays(x,y)


In [10]:
x

array([[1, 3, 4],
       [1, 3, 4],
       [1, 3, 4]])

In [11]:
y

array([[1, 1, 1],
       [3, 3, 3],
       [4, 4, 4]])

In [12]:
x*y

array([[ 1,  3,  4],
       [ 3,  9, 12],
       [ 4, 12, 16]])

In [13]:
d4=np.arange(81).reshape(3,3,3,3)
d4

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [14]:
d4.ndim

4