In [14]:
import numpy as np;
b=np.arange(16).reshape(4,4);
print(b);

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#arr[start:end:step,start:end:step]---[row,column]

In [8]:
arr=np.arange(1,37).reshape(6,6);
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
arr[2,]

array([13, 14, 15, 16, 17, 18])

In [10]:
arr[4,4]

29

In [20]:
arr[[::3,::3]]

array([[ 1,  4],
       [19, 22]])

In [3]:
import numpy as np
#three dimensional

d3=np.arange(1,51).reshape(2,5,5)
d3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [4]:
d3[0,4,4]

25

In [11]:
d3[1,0:,1]

array([27, 32, 37, 42, 47])

In [9]:
d3[0:1,2:3,0:5]

array([[[11, 12, 13, 14, 15]]])

In [14]:
d3[1,:,1:2]

array([[27],
       [32],
       [37],
       [42],
       [47]])

In [21]:
d3=np.arange(1,26).reshape(5,5)

In [7]:
 import numpy as np
data = np.arange(36).reshape(6,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
boolarr = np.array(["ahsan","farjad","asif","farjad","asif","qwerty"])
cond = (boolarr=="asif")
cond

array([False, False,  True, False,  True, False])

In [9]:
data[cond]

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [2]:
import numpy as np
empty=np.empty((4,4),dtype='int')
for i in range(4):
    empty[i]=i+1
empty

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [4]:
empty[[1,0,3]][:,[3,0,1,2]]

array([[2, 2, 2, 2],
       [1, 1, 1, 1],
       [4, 4, 4, 4]])

In [5]:
empty.T

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])